/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_fly_sky;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author SHAFIN
 */
public class Airline_Route extends javax.swing.JFrame {

    /**
     * Creates new form Airline_Route
     */
    public Airline_Route() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(662, 745));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Airline Data");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 20, 350, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Airline ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 80, 160, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Airline Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 120, 160, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("TotalSeatNo");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 160, 160, 20);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(310, 80, 260, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(310, 120, 260, 20);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(310, 160, 260, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Route Data");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 240, 350, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Route Id");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 290, 170, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Airline Id");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 320, 170, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Departure City");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 350, 170, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Departure Date");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 380, 170, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Departure Time");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 410, 170, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Arival City");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(60, 440, 170, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Arrival Date");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 470, 170, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Arrival Time");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(60, 500, 170, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Total Time For Journey");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(60, 530, 170, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Transit City");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(60, 570, 170, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Transit Time");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(60, 610, 170, 20);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(310, 290, 250, 20);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(310, 320, 250, 20);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(310, 350, 250, 20);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(310, 380, 250, 20);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(310, 410, 250, 20);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(310, 440, 250, 20);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(310, 470, 250, 20);
        jPanel1.add(jTextField11);
        jTextField11.setBounds(310, 500, 250, 20);
        jPanel1.add(jTextField12);
        jTextField12.setBounds(310, 530, 250, 20);
        jPanel1.add(jTextField13);
        jTextField13.setBounds(310, 570, 250, 20);
        jPanel1.add(jTextField14);
        jTextField14.setBounds(310, 610, 250, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 210, 140, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(310, 660, 140, 25);

        pic.setPreferredSize(new java.awt.Dimension(662, 745));
        jPanel1.add(pic);
        pic.setBounds(0, 0, 660, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int AirlineId, TotalseatNo;
        String AirlineName;
        AirlineId = Integer.parseInt(jTextField1.getText());
        AirlineName = jTextField2.getText();
        TotalseatNo = Integer.parseInt(jTextField3.getText());

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
                    .getConnection(
                            "jdbc:sqlserver://localhost:1971;databaseName=fly;selectMethod=cursor", "sa", "123456");
            System.out.println("DATABASE NAME IS:"
                    + connection.getMetaData().getDatabaseProductName());
            Statement statement = connection.createStatement();

            //            int a = statement.executeUpdate("insert into Buyer values('" + BuyerId + "','" + FirstName + "','" + LastName + "' ,'" + Address + "','" + PassportNumber + "','" + PhoneNumber + "','" + Email + "','" + RequirementName + "')");//INSERT DATA
            //            String query = "insert into Buyer values(?,?,?,?,?,?,?,?)";
            String query = "insert into Airline(AirlineId,AirlineName,TotalseatNo) values(?,?,?)";

            PreparedStatement st = connection.prepareStatement(query);
            //            st.setInt(1, BuyerId);
            st.setInt(1, AirlineId);
            st.setString(2, AirlineName);
            st.setInt(3, TotalseatNo);

            //            st.setString(8, RequirementName);
            boolean a;
            a = st.execute();//INSERT DATA
            //            System.out.println(a);
            if (a == false) {
                JOptionPane.showMessageDialog(null, "Data Inserted");
            } else {
                JOptionPane.showMessageDialog(null, "error in insertion");

            }

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int RouteId, AirlineId, TotalTimeForJourney, TransitTime;
        String DepartureCityName, DepartureDate, DepartureTime, ArrivalCityName, ArrivalDate, ArrivalTime, TransitCityName;

        RouteId = Integer.parseInt(jTextField4.getText());

        AirlineId = Integer.parseInt(jTextField5.getText());
        TotalTimeForJourney = Integer.parseInt(jTextField12.getText());
        TransitTime = Integer.parseInt(jTextField14.getText());

        DepartureCityName = jTextField6.getText();
        DepartureDate = jTextField7.getText();
        DepartureTime = jTextField8.getText();
        ArrivalCityName = jTextField9.getText();
        ArrivalDate = jTextField10.getText();

        ArrivalTime = jTextField11.getText();
        TransitCityName = jTextField13.getText();

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
                    .getConnection(
                            "jdbc:sqlserver://localhost:1971;databaseName=fly;selectMethod=cursor", "sa", "123456");
            System.out.println("DATABASE NAME IS:"
                    + connection.getMetaData().getDatabaseProductName());
            Statement statement = connection.createStatement();

            //            int a = statement.executeUpdate("insert into Buyer values('" + BuyerId + "','" + FirstName + "','" + LastName + "' ,'" + Address + "','" + PassportNumber + "','" + PhoneNumber + "','" + Email + "','" + RequirementName + "')");//INSERT DATA
            //            String query = "insert into Buyer values(?,?,?,?,?,?,?,?)";
            String query = "insert into Route(RouteId,AirlineId,DepartureCityName,DepartureDate,DepartureTime,ArrivalCityName,ArrivalDate,ArrivalTime,Jtime,TransitCity,TransitTime) values(?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement st = connection.prepareStatement(query);
            //            st.setInt(1, BuyerId);
            st.setInt(1, RouteId);

            st.setInt(2, AirlineId);
            st.setString(3, DepartureCityName);
            st.setString(4, DepartureDate);
            st.setString(5, DepartureTime);

            st.setString(6, ArrivalCityName);

            st.setString(7, ArrivalDate);
            st.setString(8, ArrivalTime);
            st.setInt(9, TotalTimeForJourney);
            st.setString(10, TransitCityName);

            st.setInt(11, TransitTime);

            //            st.setString(8, RequirementName);
            boolean a;
            a = st.execute();//INSERT DATA
            //            System.out.println(a);
            if (a == false) {
                JOptionPane.showMessageDialog(null, "Data Inserted");
            } else {
                JOptionPane.showMessageDialog(null, "error in insertion");

            }

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Airline_Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Airline_Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Airline_Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Airline_Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Airline_Route().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel pic;
    // End of variables declaration//GEN-END:variables
}
