/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_fly_sky;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author SHAFIN
 */
public class buyer_sign_up extends javax.swing.JFrame {

    /**
     * Creates new form buyer_sign_up
     */
    public buyer_sign_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buyer");

        jPanel1.setPreferredSize(new java.awt.Dimension(662, 745));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("E-mail");
        jLabel1.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 440, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("First Name");
        jLabel2.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 150, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Last Name");
        jLabel3.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 200, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Address");
        jLabel4.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 260, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Passport Number");
        jLabel5.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 320, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Phone Number");
        jLabel6.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 370, 130, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(340, 150, 200, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(340, 200, 200, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(340, 260, 200, 30);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(340, 320, 200, 30);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(340, 370, 200, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(340, 440, 200, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 520, 130, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(480, 50, 130, 30);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(270, 600, 170, 40);

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aeroplane1.jpg"))); // NOI18N
        pic.setPreferredSize(new java.awt.Dimension(662, 745));
        jPanel1.add(pic);
        pic.setBounds(0, 0, 662, 745);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
                                              
        String FirstName, LastName, Address, PhoneNumber, Email, RequirementName;
        int BuyerId, PassportNumber;
//        BuyerId = Integer.parseInt(jTextField1.getText());
        FirstName = jTextField1.getText();
        LastName = jTextField2.getText();
        Address = jTextField3.getText();
        PassportNumber = Integer.parseInt(jTextField4.getText());
        PhoneNumber = jTextField5.getText();
        Email = jTextField6.getText();
        //        RequirementName = jTextField8.getText();

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1971;databaseName=afly;selectMethod=cursor", "sa", "123456");
            System.out.println("DATABASE NAME IS:"
                + connection.getMetaData().getDatabaseProductName());
            Statement statement = connection.createStatement();

            //            int a = statement.executeUpdate("insert into Buyer values('" + BuyerId + "','" + FirstName + "','" + LastName + "' ,'" + Address + "','" + PassportNumber + "','" + PhoneNumber + "','" + Email + "','" + RequirementName + "')");//INSERT DATA
            //            String query = "insert into Buyer values(?,?,?,?,?,?,?,?)";
            String query = "insert into Buyer(FirstName,LastName,Address,PassportNumber,PhoneNumber,Email) values(?,?,?,?,?,?)";
String q1="select buyerid from buyer where FirstName=? AND LastName=? AND Address=? AND PassportNumber=? AND PhoneNumber=? AND Email=?";
            PreparedStatement st = connection.prepareStatement(query);
             PreparedStatement st1 = connection.prepareStatement(q1);
            //            st.setInt(1, BuyerId);
            st.setString(1, FirstName);
            st.setString(2, LastName);
            st.setString(3, Address);
            st.setInt(4, PassportNumber);
            st.setString(5, PhoneNumber);
            st.setString(6, Email);
             st1.setString(1, FirstName);
            st1.setString(2, LastName);
            st1.setString(3, Address);
            st1.setInt(4, PassportNumber);
            st1.setString(5, PhoneNumber);
            st1.setString(6, Email);
//            ResultSet rs=null;
//            rs=st1.executeQuery();
            jLabel7.setText(st1.executeQuery().toString());
            //            st.setString(8, RequirementName);
            boolean a;
            a = st.execute();//INSERT DATA
            //            System.out.println(a);
            if (a==false) {
                JOptionPane.showMessageDialog(null, "Data Inserted");
                this.setVisible(false);
              new SearchForFlight().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "error in insertion");

            }

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:.
         
        this.setVisible(false);
        new InsertOption().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buyer_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buyer_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buyer_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buyer_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buyer_sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel pic;
    // End of variables declaration//GEN-END:variables
}
