/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_fly_sky;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author SHAFIN
 */
public class EconomyClass extends javax.swing.JFrame {

    /**
     * Creates new form Class_data
     */
    public EconomyClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(662, 745));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Economy Class");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 30, 270, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Route Id");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 110, 190, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Airline Id");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 170, 190, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Class Base Fare");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 230, 190, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("DepartureCity ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 280, 190, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Departure DATE");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 340, 190, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Departure Time");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 400, 190, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Arrival City");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(60, 440, 190, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Seat Number");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 480, 190, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Special requirement");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(60, 530, 190, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Journey Time(hr)");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(60, 570, 190, 17);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(270, 110, 220, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(270, 170, 220, 20);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(270, 230, 220, 20);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(270, 280, 220, 20);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(270, 400, 220, 20);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(270, 440, 220, 20);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(270, 480, 220, 20);
        jPanel1.add(jTextField11);
        jTextField11.setBounds(270, 530, 220, 20);
        jPanel1.add(jTextField12);
        jTextField12.setBounds(270, 570, 220, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(530, 650, 90, 25);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(540, 30, 90, 25);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Transit City");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(60, 610, 190, 17);
        jPanel1.add(jTextField13);
        jTextField13.setBounds(270, 610, 220, 20);
        jPanel1.add(jTextField14);
        jTextField14.setBounds(270, 650, 220, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Transit Time");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(60, 650, 190, 17);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(270, 330, 220, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aeroplane1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 662, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ClassOption().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int SeatId, AirlineId, TotalTimeForJourney, TransitTime;
        String RouteId, DepartureCityName, DepartureDate, DepartureTime, ArrivalCityName, ClassBaseFare, SeatNumber, SpecialRequirementName, TransitCityName;

//        SeatId = Integer.parseInt(jTextField1.getText());
        RouteId = jTextField3.getText();
        AirlineId = Integer.parseInt(jTextField4.getText());
        ClassBaseFare = jTextField5.getText();
        DepartureCityName = jTextField6.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        DepartureDate = sdf.format(jDateChooser1.getDate());
        DepartureTime = jTextField8.getText();

        ArrivalCityName = jTextField9.getText();
        SeatNumber = jTextField10.getText();
        SpecialRequirementName = jTextField11.getText();
        TotalTimeForJourney = Integer.parseInt(jTextField12.getText());
        TransitTime = Integer.parseInt(jTextField14.getText());

        TransitCityName = jTextField13.getText();

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
                    .getConnection(
                            "jdbc:sqlserver://localhost:1971;databaseName=afly;selectMethod=cursor", "sa", "123456");
            System.out.println("DATABASE NAME IS:"
                    + connection.getMetaData().getDatabaseProductName());
            Statement statement = connection.createStatement();

           
            String query = "insert into Economyclass(RouteId,AirLineId,ClassBaseFare,DepartureCity,DepartureDATE,DepartureTime,ArrivalCity,SeatNumber,SpecialRequirementName,Jtime,TransitCity,TransitTime) values(?,?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement st = connection.prepareStatement(query);
           
            st.setString(1, RouteId);

            st.setInt(2, AirlineId);
            st.setString(3, ClassBaseFare);
            st.setString(4, DepartureCityName);
            st.setString(5, DepartureDate);

            st.setString(6, DepartureTime);

            st.setString(7, ArrivalCityName);
            st.setString(8, SeatNumber);
            st.setString(9, SpecialRequirementName);
             st.setInt(10, TotalTimeForJourney);

            st.setString(11, TransitCityName);

            st.setInt(12, TransitTime);

            //            st.setString(8, RequirementName);
            boolean a;
            a = st.execute();//INSERT DATA
            //            System.out.println(a);
            if (a == false) {
                JOptionPane.showMessageDialog(null, "Data Inserted");
            } else {
                JOptionPane.showMessageDialog(null, "error in insertion");

            }

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EconomyClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EconomyClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EconomyClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EconomyClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EconomyClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
